### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by android4canada** [suddh123/YOLO-object-detection-in-java#1]
Hello,
Thank you for your work. I am trying to run your program . I am on java 1.8 and openCv 4.1.0 and the program is crashing with the following
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\matrix.cpp:406: error: (-215:Assertion failed) m.dims >= 2 in function 'cv::Mat::Mat'
]
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:139)
	at org.opencv.core.MatOfFloat.<init>(MatOfFloat.java:27)

The exception is happening at this line
MatOfFloat confidences = new MatOfFloat(Converters.vector_float_to_Mat(confs));

Any idea why or how to fix it?

Thank you

**Comment by Aboumouadine** [comment]
@android4canada Have you solved this issue? I am currently struggling with it.
